CREATE PROCEDURE ObtenerRolUsuario
(
@DNIUSU varchar(9)
)
AS
SELECT 
DNI_USU			AS DNI,
ROL.ID_ROL		AS ID_ROL,
ROL.ROL			AS ROL
FROM 
USUARIOS
inner join ROL ON USUARIOS.ID_ROL_USU = ID_ROL
WHERE ESTADO_USU = 1
AND DNI_USU = @DNIUSU