<%@ Page Title="" Language="C#" MasterPageFile="~/Cliente/PaginaMaestraCliente.master" AutoEventWireup="true" CodeBehind="CarritoCliente.aspx.cs" Inherits="CapaPresentacion.Cliente.CarritoCliente" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadCliente" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContenidoColIzCliente" runat="server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContenidoColPpalCliente" runat="server">
    
    <div id="CarritoEmpleado" class="Form">
        <h2>Mi Carrito</h2>
       
        <asp:Label ID="lblIdVenta" runat="server" Text="Venta N°: " CssClass="LabelNegrita" ></asp:Label>
        <asp:Label ID="txtIdVenta" runat="server" Text="xxx-0001" CssClass="Label" ></asp:Label>
        <asp:Label ID="lblFecha" runat="server" Text="Fecha: "  CssClass="LabelNegrita" ></asp:Label>
        <asp:Label ID="txtFecha" runat="server" Text="04/11/2019"  CssClass="Label" ></asp:Label>
        <asp:Label ID="lblLegajo" runat="server" Text="Vendedor: "  CssClass="LabelNegrita" ></asp:Label>
        <asp:Label ID="txtLegajo" runat="server" Text="E-99999999"  CssClass="Label" ></asp:Label>       
        <asp:Label ID="lblDNICliente" runat="server" Text="Cliente: "  CssClass="LabelNegrita" ></asp:Label>
        <asp:Label ID="txtDNICliente" runat="server" Text="35767657"  CssClass="Label" ></asp:Label>       
        <asp:Label ID="lblFormaPago" runat="server" Text="Forma de pago: "  CssClass="LabelNegrita" ></asp:Label>
        <asp:DropDownList ID="ddlFPago" runat="server" CssClass="DropDownList" ></asp:DropDownList>
        <asp:Label ID="lblFormaEnvio" runat="server" Text="Forma de envio: "  CssClass="LabelNegrita" ></asp:Label>
        <asp:DropDownList ID="ddlFEnvio" runat="server" CssClass="DropDownList"></asp:DropDownList>
        <asp:Label ID="lblImporte" runat="server" Text="Importe a pagar: $"  CssClass="LabelNegritaLarga" ></asp:Label>
        
        <asp:Button ID="bttnAgregarItem" runat="server" Text="Agregar otro item" CssClass="Boton" OnClick="bttnAgregarItem_Click" />
        <asp:Button ID="bttnFinalizarcompra" runat="server" Text="Confirmar compra" CssClass="Boton" OnClick="bttnFinalizarcompra_Click" />

   
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" HorizontalAlign="Center">
            <Columns>
                <asp:TemplateField HeaderText="Modelo"></asp:TemplateField>
                <asp:TemplateField HeaderText="Precio"></asp:TemplateField>
                <asp:TemplateField HeaderText="Cantidad" ValidateRequestMode="Enabled"></asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
            <RowStyle BackColor="White" ForeColor="#003399" />
            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
            <SortedAscendingCellStyle BackColor="#EDF6F6" />
            <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
            <SortedDescendingCellStyle BackColor="#D6DFDF" />
            <SortedDescendingHeaderStyle BackColor="#002876" />
        </asp:GridView>

   
    </div>
  
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContenidoColDerCliente" runat="server">
</asp:Content>
