CREATE Procedure ModificarUsuarioEmpleados
	@DNIUSU varchar(15),
	@NOMBREUSU varchar(30),
	@APELLIDOUSU varchar(30),
	@TELEFONOUSU varchar(20),
	@PROVINCIAUSU int,
	@LOCALIDADUSU int,
	@DIRRECIONUSU varchar(30),
	@ROL varchar(1)
AS
UPDATE USUARIOS
SET	
	DNI_USU = @DNIUSU,
	NOMBRE_USU = @NOMBREUSU, 
	APELLIDO_USU = @APELLIDOUSU, 
	TELEFONO_USU = @TELEFONOUSU, 
	ID_PROVINCIA_USU=@PROVINCIAUSU,
	ID_LOCALIDAD_USU=@LOCALIDADUSU,
	DIRECCION_USU = @DIRRECIONUSU, 
	ID_ROL_USU = @ROL
WHERE DNI_USU = @DNIUSU