CREATE PROCEDURE ObtenerDatosUsuario
(
@DNIUSU varchar(15)
)
AS
SELECT 
DNI_USU					AS DNI,
NOMBRE_USU				AS NOMBRE,
APELLIDO_USU			AS APELLIDO,
TELEFONO_USU			AS TELEFONO,
P.descripcion_provincia	AS PROVINCIA,
L.desc_localidad		AS LOCALIDAD,
DIRECCION_USU			AS DIRECCION,
CONTRASEÑA				AS CONTRASENA
FROM 
USUARIOS U
INNER JOIN PROVINCIAS P ON P.cod_provincia = U.ID_PROVINCIA_USU
INNER JOIN LOCALIDADES L ON L.cod_postal = U.ID_LOCALIDAD_USU
WHERE ESTADO_USU = 1
AND DNI_USU = @DNIUSU